insert into xmp_content_sent (
  tid,
  sent_at,
  msisdn,
  id_campaign,
  id_service,
  id_content,
  id_subscription,
  operator_code,
  country_code
) select tid,
                sent_at,
                msisdn,
                id_campaign,
                id_service,
                id_content,
                id_subscription,
                operator_code,
                country_code
from xmp_content_sent_2016_12_16;




  insert into xmp_campaigns_access(
  tid ,
  sent_at ,
  msisdn ,
  ip ,
  operator_code ,
  country_code ,
  supported ,
  user_agent,
  referer ,
  url_path ,
  method ,
  headers,
  error ,
  id_campaign ,
  id_service ,
  id_content ,
  geoip_country ,
  geoip_iso ,
  geoip_city,
  geoip_timezone ,
  geoip_latitude ,
  geoip_longitude,
  geoip_metro_code ,
  geoip_postal_code,
  geoip_subdivisions ,
  geoip_is_anonymous_proxy ,
  geoip_is_satellite_provider ,
  geoip_accuracy_radius ,
  os ,
  device ,
  browser,
  created_at
) select tid ,
                  sent_at ,
                  msisdn ,
                  ip ,
                  operator_code ,
                  country_code ,
                  supported ,
                  user_agent,
                  referer ,
                  url_path ,
                  method ,
                  headers,
                  error ,
                  id_campaign ,
                  id_service ,
                  id_content ,
                  geoip_country ,
                  geoip_iso ,
                  geoip_city,
                  geoip_timezone ,
                  geoip_latitude ,
                  geoip_longitude,
                  geoip_metro_code ,
                  geoip_postal_code,
                  geoip_subdivisions ,
                  geoip_is_anonymous_proxy ,
                  geoip_is_satellite_provider ,
                  geoip_accuracy_radius ,
                  os ,
                  device ,
                  browser,
                  created_at from xmp_campaigns_access_2016_12_16;



insert into xmp_operator_transaction_log(
  created_at ,
  tid ,
  msisdn ,
  operator_code ,
  country_code ,
  operator_token ,
  error ,
  price ,
  id_service ,
  id_subscription ,
  id_campaign ,
  request_body,
  response_body ,
  response_decision ,
  response_code ,
  sent_at
) select created_at ,
                tid ,
                msisdn ,
                operator_code ,
                country_code ,
                operator_token ,
                error ,
                price ,
                id_service ,
                id_subscription ,
                id_campaign ,
                request_body,
                response_body ,
                response_decision ,
                response_code ,
                sent_at from xmp_operator_transaction_log_2016_12_16;




insert into xmp_pixel_transactions(
  created_at ,
  tid ,
  msisdn ,
  id_campaign ,
  operator_code,
  country_code ,
  pixel ,
  publisher ,
  response_code ,
  endpoint ,
  sent_at
) select created_at ,
                tid ,
                msisdn ,
                id_campaign ,
                operator_code,
                country_code ,
                pixel ,
                publisher ,
                response_code ,
                endpoint ,
                sent_at from xmp_pixel_transactions_2016_12_16;

CREATE INDEX xmp_subscriptions_sent_at_idx ON xmp_subscriptions (sent_at);
CREATE INDEX xmp_subscriptions_last_pay_attempt_at_idx ON xmp_subscriptions (last_pay_attempt_at);
insert into xmp_subscriptions(
  last_request_at ,
  id_service ,
  country_code,
  created_at ,
  msisdn ,
  operator_code ,
  id_campaign ,
  attempts_count ,
  price ,
  result ,
  keep_days ,
  last_pay_attempt_at ,
  paid_hours ,
  delay_hours ,
  tid ,
  pixel ,
  publisher ,
  pixel_sent ,
  pixel_sent_at ,
  sent_at
) select last_request_at ,
                id_service ,
                country_code,
                created_at ,
                msisdn ,
                operator_code ,
                id_campaign ,
                attempts_count ,
                price ,
                result ,
                keep_days ,
                last_pay_attempt_at ,
                paid_hours ,
                delay_hours ,
                tid ,
                pixel ,
                publisher ,
                pixel_sent ,
                pixel_sent_at ,
                sent_at from xmp_subscriptions_2016_12_16;




insert into xmp_transactions
(
  created_at ,
  msisdn ,
  country_code ,
  id_service ,
  operator_code ,
  id_subscription ,
  operator_token ,
  price ,
  result ,
  id_campaign ,
  tid ,
  sent_at
) select
                created_at ,
                msisdn ,
                country_code ,
                id_service ,
                operator_code ,
                id_subscription ,
                operator_token ,
                price ,
                result ,
                id_campaign ,
                tid ,
                sent_at from xmp_transactions_2016_12_16;




insert into xmp_user_actions
(
  tid ,
  action ,
  error ,
  sent_at ,
  created_at ,
  id_campaign ,
  msisdn
) select
                tid ,
                action ,
                error ,
                sent_at ,
                created_at ,
                id_campaign ,
                msisdn  from xmp_user_actions_2016_12_16