TRUNCATE TABLE public.xmp_subscriptions CONTINUE IDENTITY RESTRICT;
TRUNCATE TABLE public.xmp_user_actions CONTINUE IDENTITY RESTRICT;
TRUNCATE TABLE public.xmp_campaigns_access CONTINUE IDENTITY RESTRICT;
TRUNCATE TABLE public.xmp_content_sent CONTINUE IDENTITY RESTRICT;

TRUNCATE TABLE public.xmp_transactions CONTINUE IDENTITY RESTRICT;
TRUNCATE TABLE public.xmp_pixel_transactions CONTINUE IDENTITY RESTRICT;
TRUNCATE TABLE public.xmp_operator_transaction_log CONTINUE IDENTITY RESTRICT;

TRUNCATE TABLE public.xmp_retries CONTINUE IDENTITY RESTRICT;
TRUNCATE TABLE public.xmp_retries_expired CONTINUE IDENTITY RESTRICT;

TRUNCATE TABLE public.xmp_msisdn_blacklist CONTINUE IDENTITY RESTRICT;
TRUNCATE TABLE public.xmp_msisdn_postpaid CONTINUE IDENTITY RESTRICT;
TRUNCATE TABLE public.xmp_pixel_buffer CONTINUE IDENTITY RESTRICT;
